package com.ntian.videoplayer.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIDEO_SCAN_RECORDS.
 */
public class VideoScanRecords {

    private Long id;
    private Long Base_ID;
    private Boolean Is_Scanned;
    private Long PlayedPosition;
    private java.util.Date Last_Played;
    private String Video_path;
    private Long Time_Flag;
    private String Title;
    private Long Duration;
    private Long DateModified;
    private Boolean IsDrm;
    private Boolean Support3D;

    public VideoScanRecords() {
    }

    public VideoScanRecords(Long id) {
        this.id = id;
    }

    public VideoScanRecords(Long id, Long Base_ID, Boolean Is_Scanned, Long PlayedPosition, java.util.Date Last_Played, String Video_path, Long Time_Flag, String Title, Long Duration, Long DateModified, Boolean IsDrm, Boolean Support3D) {
        this.id = id;
        this.Base_ID = Base_ID;
        this.Is_Scanned = Is_Scanned;
        this.PlayedPosition = PlayedPosition;
        this.Last_Played = Last_Played;
        this.Video_path = Video_path;
        this.Time_Flag = Time_Flag;
        this.Title = Title;
        this.Duration = Duration;
        this.DateModified = DateModified;
        this.IsDrm = IsDrm;
        this.Support3D = Support3D;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBase_ID() {
        return Base_ID;
    }

    public void setBase_ID(Long Base_ID) {
        this.Base_ID = Base_ID;
    }

    public Boolean getIs_Scanned() {
        return Is_Scanned;
    }

    public void setIs_Scanned(Boolean Is_Scanned) {
        this.Is_Scanned = Is_Scanned;
    }

    public Long getPlayedPosition() {
        return PlayedPosition;
    }

    public void setPlayedPosition(Long PlayedPosition) {
        this.PlayedPosition = PlayedPosition;
    }

    public java.util.Date getLast_Played() {
        return Last_Played;
    }

    public void setLast_Played(java.util.Date Last_Played) {
        this.Last_Played = Last_Played;
    }

    public String getVideo_path() {
        return Video_path;
    }

    public void setVideo_path(String Video_path) {
        this.Video_path = Video_path;
    }

    public Long getTime_Flag() {
        return Time_Flag;
    }

    public void setTime_Flag(Long Time_Flag) {
        this.Time_Flag = Time_Flag;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Long getDuration() {
        return Duration;
    }

    public void setDuration(Long Duration) {
        this.Duration = Duration;
    }

    public Long getDateModified() {
        return DateModified;
    }

    public void setDateModified(Long DateModified) {
        this.DateModified = DateModified;
    }

    public Boolean getIsDrm() {
        return IsDrm;
    }

    public void setIsDrm(Boolean IsDrm) {
        this.IsDrm = IsDrm;
    }

    public Boolean getSupport3D() {
        return Support3D;
    }

    public void setSupport3D(Boolean Support3D) {
        this.Support3D = Support3D;
    }

}
